# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.estr2525.github.io
title: Samantha Estrada PhD
email: estr2525@gmail.com
author: Samantha Estrada
description: "MyName's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/NyName 
  - icon: envelope-o
    title: email
    url: mailto:NyName@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/NyName/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/estr2525

